# Generated by Django 2.1 on 2018-08-07 20:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plates', models.CharField(max_length=30, unique=True)),
                ('model', models.CharField(max_length=30)),
                ('isIn', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.date.today)),
                ('type', models.CharField(default='False Alarm', max_length=30)),
                ('house', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SecureDoomDB.House')),
            ],
        ),
        migrations.CreateModel(
            name='InOutRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=datetime.date.today)),
                ('kind', models.CharField(max_length=3)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SecureDoomDB.Car')),
            ],
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SecureDoomDB.House')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='incident',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SecureDoomDB.Sensor'),
        ),
        migrations.AddField(
            model_name='incident',
            name='street',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='street_name', to='SecureDoomDB.Street'),
        ),
        migrations.AddField(
            model_name='house',
            name='private_street',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SecureDoomDB.Street'),
        ),
        migrations.AddField(
            model_name='car',
            name='propietary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SecureDoomDB.Resident'),
        ),
    ]
